config/routes.rb
Rails.application.routes.draw do
  root to: 'maps#index'
  resources :maps, only: [:index, :show] do
    resources :posts, only: [:create]
    resources :comments, only: [:create]
  end
  get '/map_request', to: 'maps#map', as: 'map_request'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :map
end

app/models/evaluation.rb
class Evaluation < ActiveHash::Base
  self.data = [
    {id: 1, name: '---------'},
    {id: 2, name: '1(悪い)'},
    {id: 3, name: '2(微妙)'},
    {id: 4, name: '3(普通)'},
    {id: 5, name: '4(良い)'},
    {id: 6, name: '5(とても良い)'}
  ]
  include ActiveHash::Associations
  has_many :posts
end

app/models/map.rb
class Map < ApplicationRecord
  has_many :posts
  has_many :comments
end

app/models/post.rb
class Post < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :map
  belongs_to :evaluation

  validates :context, presence: true
  validates :evaluation_id, numericality: {other_than: 1}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @map = Map.find(params[:map_id])
    comment = Comment.create(comment_params)
    redirect_to "/maps/#{comment.map_id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:context).merge(map_id: params[:map_id])
  end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
    @maps = Map.all
    gon.maps = Map.all
  end

  def show
    @map = Map.find(params[:id])
    @post = Post.new
    @posts = @map.posts
    @comment = Comment.new
    @comments = @map.comments
  end

  def map
    results = Geocoder.search(params[:address])
    @latlng = results.first.coordinates
    # これでmap.js.erbで、経度緯度情報が入った@latlngを使える。
  
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def create
    @map = Map.find(params[:map_id])
    post= Post.create(post_params)
    redirect_to "/maps/#{post.map.id}"
  end

  private
  def post_params
    params.require(:post).permit(:context, :evaluation_id).merge(map_id: params[:map_id] )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoogleapiPractice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= include_gon %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/maps/index.html.erb
<h2>gmap</h2>

<%= form_with url: map_request_path, method: :get do |f|%>
  <%= f.text_field :address%>
  <%= f.submit '地図表示'%>
<% end %>

<div id='map'></div>

<style>
#map{
  height: 500px;
}
</style>

<script>

const locations = [
  { name: "東京タワー", lat: 35.6585805, lng: 139.7454329, id:1 },
  { name: "京都タワー", lat: 34.9875441, lng: 135.7592164, id:2 },
  { name: "通天閣", lat: 34.6524992, lng: 135.5063058, id:3 }
];

let map;
const maps = gon.maps;

function initMap(){
  map = new google.maps.Map(document.getElementById('map'), {
  center: {lat: 33.514425, lng: 139.311842},
  zoom: 7
  });

let currentWindow;

  locations.map(d => {
    // マーカーをつける
    const marker = new google.maps.Marker({
      position: {lat: d.lat, lng: d.lng},
      map: map
    });

    // マーカークリックしたら地名をポップアップさせる
    marker.addListener('click', () => {
      currentWindow && currentWindow.close();
      const url= `<%= link_to "${d.name}", "/maps/${d.id}" %>`
      const infoWindow = new google.maps.InfoWindow({content: url});
      infoWindow.open(map, marker);
      currentWindow = infoWindow;
    });
  });
}


</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLEMAP_API'] %>&callback=initMap" async defer></script>

app/views/maps/map.js.erb
(function(){
  let pos = new google.maps.LatLng(
   <%= @latlng[0] %>, //latitude
   <%= @latlng[1] %>  //longitude
  );

  map.setCenter(pos)
  let marker = new google.maps.Marker({
    map: map,
    position: pos
  });
})()

app/views/maps/show.html.erb
<h1>showファイル</h1>
<div><%= @map.name%></div>
<%= image_tag "island_#{@map.id}.png", class: "island_image"%>
<style>
.island_image {
  height: 500px;
  width: 500px;
}
</style>

  <div class="container">
      <%= form_with(model: [@map, @post], local: true) do |form| %>
        <%= form.text_area :context, placeholder: "投稿する", rows: "5" %>
        <%= form.collection_select(:evaluation_id, Evaluation.all, :id, :name, {}, {class: "evaluation-select"})%>
        <%= form.submit "SEND" %>
      <% end %>
  </div>

    <div class="comments">
    <h4>＜投稿一覧＞</h4>
      <% if @posts %>
        <% @posts.each do |post| %>
          <p>
            <%= post.context %>
            <%= post.evaluation.name%>
          </p>
        <% end %>
      <% end %>
  </div>

  <div class="container">
      <%= form_with(model: [@map, @comment], local: true) do |form| %>
        <%= form.text_area :context, placeholder: "投稿する", rows: "5" %>
        <%= form.submit "SEND" %>
      <% end %>
  </div>

    <div class="comments">
    <h4>＜コメント欄＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <%= comment.context %>
          </p>
        <% end %>
      <% end %>
  </div>